###
GET http://localhost:3000/bailleurs/11

###
POST http://localhost:3000/bailleurs
content-type: application/json

{   
    "nom": "Happy Wandja",
    "prenom": "Paul Fernand",
    "residence_ids": [1, 3]
}